Feature/note status clear
Lambda-School-Labs/mission-control-fe pull request #244
Opened 2020-03-10 23:03 UTC by CalebAllard

# Description
 Added style to Private and Public buttons on notes. Re-added Project Manager to Project view team list. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status
- [x] Complete, tested, ready to review and merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2020-03-10 23:09 UTC, lawsonarichard requested changes
Make the changes as following

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteEditor/NoteEditor.module.scss
> +.notewraperPrivit {
change to` .notewrapperPrivate`

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteFeed/Note/Notes.module.scss
> +.notewraperPublic {
change to
`.notewrapperPublic`

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteFeed/Note/Notes.module.scss
> +.notewraperPrivit {
change to `.notewrapperPrivate`

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteFeed/Note/index.jsx
> +  notewraperPrivit,
change to 
`notewrapperPrivate`

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteFeed/Note/index.jsx
> +  notewraperPublic,
change to `.notewrapperPublic`

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteFeed/Note/index.jsx
> +              <div onClick={() => setIsEditing(true)} class={notewraperPrivit}>Private Note</div>
change to 
`class={notewrapperPrivate}`

2020-03-10 23:09 UTC, lawsonarichard commented on src/components/Project/NoteFeed/Note/index.jsx
> +              : <div onClick={() => setIsEditing(true)} class={notewraperPublic}>Public Note</div>}
change to
`class={notewrapperPublic}`

2020-03-16 20:38 UTC, lawsonarichard approved these changes

2020-03-16 21:55 UTC, lawsonarichard approved these changes
pulled down, tested functions for all components on project single view page

2020-03-16 22:45 UTC, Memitaru commented on src/components/Project/NoteEditor/index.jsx
> +				/*START OF FIX
Thanks for the note and documentation on the PR. Very helpful. 👍

2020-03-16 22:45 UTC, Memitaru approved these changes
Works for me, looks great 👍

2020-03-16 22:47 UTC, merged